### ISSUE TITLE
'Synchronize the entire collection' crashes Rhythmbox

### ISSUE THREAD

**Issue by hotice** [BramBonne/LastfmPlaycount#4]
When I click the 'Synchronize the entire collection' button and then try to play a song, Rhythmbox crashes. 

Here's the output:
(rhythmbox:30747): libpeas-CRITICAL **: show_configure_cb: assertion `GTK_IS_WIDGET (conf_widget)' failed
/usr/lib/python2.7/dist-packages/gi/types.py:43: Warning: g_value_get_uint: assertion `G_VALUE_HOLDS_UINT (value)' failed
  return info.invoke(*args, **kwargs)
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
**
ERROR:/build/buildd/pygobject-3.0.0/gi/_gobject/pygobject.c:929:pygobject_new_full: assertion failed: (tp != NULL)
Aborted

Using Rhythmbox 2.95 / Ubuntu 11.10.

**Comment by BramBonne** [comment]
After about 4 years I got around to fixing this bug by modifying the plugin to use some of the rhythmbox 3 specifics. Because rhythmbox 3 intentionally broke backwards compatibility for plugins, this means that the plugin will no longer work with versions of rhythmbox < 3. However, I consider rhythmbox 3 to be mature enough that almost no one should be using the older versions anyway.

Please let me know if you should encounter this bug again in the latest version of the plugin.
